package com.example.reportgenerator.storage;
import com.example.reportgenerator.config.MinioProperties;import com.example.reportgenerator.model.*;import io.minio.*;import org.springframework.stereotype.Service;import java.io.*;import java.time.Instant;import java.util.*;
@Service
public class MinioArchiveService { private final MinioClient client; private final MinioProperties props; private final MetadataService metadataService; public MinioArchiveService(MinioClient c,MinioProperties p,MetadataService m){client=c;props=p;metadataService=m;}
 public void archive(LabReport r,String sourceFilename,byte[] xml,byte[] pdf){ try{ if(!client.bucketExists(BucketExistsArgs.builder().bucket(props.bucket()).build())) client.makeBucket(MakeBucketArgs.builder().bucket(props.bucket()).build()); String ref=blank(r.referenceNumber())?"UNKNOWN_REFERENCE":r.referenceNumber(); String base="patients/"+r.patientStorageId()+"/"+ref+"/"; String xmlPath=base+ref+".xml", pdfPath=base+ref+".pdf", metaPath=base+"metadata.json"; String ts=Instant.now().toString(); String xmlSha=ChecksumUtil.sha256(xml), pdfSha=ChecksumUtil.sha256(pdf); var meta=metadataService.build(r,sourceFilename,xmlSha,pdfSha,ts,xmlPath,pdfPath); put(xmlPath,xml,"application/xml",objectMeta(r,"XML",sourceFilename,ts,xmlSha)); put(pdfPath,pdf,"application/pdf",objectMeta(r,"PDF",sourceFilename,ts,pdfSha)); byte[] mj=metadataService.json(meta); put(metaPath,mj,"application/json",objectMeta(r,"METADATA",sourceFilename,ts,ChecksumUtil.sha256(mj))); }catch(Exception e){throw new IllegalStateException("MinIO archive failed",e);} }
 private void put(String object,byte[] bytes,String contentType,Map<String,String> meta) throws Exception{ client.putObject(PutObjectArgs.builder().bucket(props.bucket()).object(object).stream(new ByteArrayInputStream(bytes),bytes.length,-1).contentType(contentType).userMetadata(meta).build()); }
 private Map<String,String> objectMeta(LabReport r,String type,String file,String ts,String sha){ Map<String,String> m=new HashMap<>(); Patient p=r.patient(); Physician ph=r.physician(); m.put("referenceNumber",n(r.referenceNumber()));m.put("patientInternalId",n(p==null?null:p.internalId()));m.put("ssnPatient",n(r.ssnPatient()));m.put("patientLastName",n(p==null?null:p.lastName()));m.put("patientFirstName",n(p==null?null:p.firstName()));m.put("patientBirthdate",n(p==null?null:p.birthdate()));m.put("physicianCode",n(ph==null?null:ph.codeUcm()));m.put("physicianName",n(ph==null?null:ph.fullName()));m.put("specimenDate",n(r.specimenDate()));m.put("validationDate",n(r.validationDate()));m.put("examinationStatus",n(r.examinationStatus()));m.put("targetLanguage",n(r.targetLanguage()));m.put("documentType",type);m.put("sourceFilename",file);m.put("uploadTimestamp",ts);m.put("checksumSha256",sha);return m; }
 private static String n(String s){return s==null?"":s;} private static boolean blank(String s){return s==null||s.isBlank();}
}
